#!/usr/bin/with-contenv bashio

CONFIG="/etc/ddclient/ddclient.conf"

DDCLIENT_CONFIG=$(bashio::config 'config')
DDNS_PROTOCOL=$(bashio::config 'ddns_protocol')
CHECK_INTERVAL=$(bashio::config 'check_interval')
RETRY_INTERVAL=$(bashio::config 'retry_interval')

# Build base config
cat > "$CONFIG" <<EOL
daemon=${CHECK_INTERVAL}                    # check every N seconds
retry=${RETRY_INTERVAL}                     # retry after failed update in N seconds
syslog=yes                                  # log update msgs to syslog
pid=/run/ddclient/ddclient.pid              # record PID in file
ssl=yes                                     # use ssl support
EOL

# Configure IP detection mode
case "$DDNS_PROTOCOL" in
  "ipv4 only")
    cat >> "$CONFIG" <<EOL
usev4=webv4
webv4=api.ipify.org
EOL
    ;;
  "ipv6 only")
    cat >> "$CONFIG" <<EOL
usev6=webv6
webv6=api6.ipify.org
EOL
    ;;
  "both")
    cat >> "$CONFIG" <<EOL
usev4=webv4
webv4=api.ipify.org
usev6=webv6
webv6=api6.ipify.org
EOL
    ;;
  *)
    bashio::log.fatal "Unsupported ddns_protocol: ${DDNS_PROTOCOL}"
    exit 1
    ;;
esac

echo "" >> "$CONFIG"
echo "## < -- Autogenerated config below this line -->" >> "$CONFIG"

# Process each JSON object in the config
echo "$DDCLIENT_CONFIG" | while IFS= read -r line; do
    # Skip empty lines
    [ -z "$line" ] && continue

    # Parse the JSON and create config section
    zone=$(echo "$line" | jq -r '.zone')
    token=$(echo "$line" | jq -r '.token')
    domains=$(echo "$line" | jq -r '.domains')

    # Append configuration section for this entry
    cat >> "$CONFIG" << EOL
protocol=cloudflare
zone=${zone}
ttl=1
login=token
password=${token}
${domains}
EOL
done

# Start ddclient
ddclient -foreground -verbose -debug
